"""Capability tables: TCLV parameters, status enums, panel geometry.

Leaf package. Depends on nothing in :mod:`pyvisionect.wire` or
:mod:`pyvisionect.session` (except :mod:`pyvisionect.wire.errors`, for the
read-only-parameter error).
"""

from .enums import (
    CHARGING_STATUS,
    CONNECT_REASON,
    CONNECTIVITY_USED,
    DCM_STATE,
    ERROR_CODE,
    HARDWARE_FAMILY,
    JS_APP_TYPE,
    PV2_FEATURE_BITS,
    QSPI_FLASH_ID,
    RENDERER,
    SCPU_SENSOR_BITS,
    TOUCH_TYPE,
    CommandType,
    ControlFlags,
    EncodingType,
    FileMode,
    FileOperation,
    ImageType,
    PacketType,
    ParamControl,
    describe,
)
from .panels import (
    DEFAULT_PANEL,
    DISPLAY_TYPE_DRIVER,
    DISPLAY_TYPE_NAMES,
    DRIVERS,
    PANELS,
    Driver,
    Panel,
    display_type_name,
    driver_for,
    panel_for,
)
from .tclv import (
    NETWORK_READ_ONLY,
    TCLV,
    USB_HINTS,
    TclvEntry,
    check_writable,
    lookup,
    name_of,
)

__all__ = [
    "CHARGING_STATUS",
    "CONNECTIVITY_USED",
    "CONNECT_REASON",
    "CommandType",
    "ControlFlags",
    "DCM_STATE",
    "DEFAULT_PANEL",
    "DISPLAY_TYPE_DRIVER",
    "DISPLAY_TYPE_NAMES",
    "DRIVERS",
    "Driver",
    "ERROR_CODE",
    "EncodingType",
    "FileMode",
    "FileOperation",
    "HARDWARE_FAMILY",
    "ImageType",
    "JS_APP_TYPE",
    "NETWORK_READ_ONLY",
    "PANELS",
    "PV2_FEATURE_BITS",
    "PacketType",
    "Panel",
    "ParamControl",
    "QSPI_FLASH_ID",
    "RENDERER",
    "SCPU_SENSOR_BITS",
    "TCLV",
    "TOUCH_TYPE",
    "TclvEntry",
    "USB_HINTS",
    "check_writable",
    "describe",
    "display_type_name",
    "driver_for",
    "lookup",
    "name_of",
    "panel_for",
]
