"""Wire layer: framing, the LZ4 block chain, and the direction-dependent CRC.

Pure. No sockets, no clock.
"""

from .blocks import (
    BLOCK_HEADER_SIZE,
    BLOCK_PLAINTEXT_SIZE,
    STORED_ONLY,
    BlockHeader,
    decode_blocks,
    encode_blocks,
    have_lz4,
    iter_block_headers,
    lz4_compress_block,
    lz4_decompress_block,
    stored_only,
)
from .checksum import Direction, crc32_ieee, frame_checksum, verify_checksum
from .errors import (
    BlockError,
    ChecksumMismatch,
    CommandPacketsDisabled,
    ListenError,
    MissingLz4,
    FrameTooLarge,
    PayloadError,
    ProtocolError,
    ReadOnlyParameter,
    ShortBuffer,
    UnsupportedCompression,
    UnsupportedSecurity,
    UnsupportedVersion,
    VisionectError,
)
from .framing import (
    DATA_HEADER_SIZE,
    MAX_FRAME_LENGTH,
    PROTOCOL_HEADER_SIZE,
    PROTOCOL_VERSION,
    Compression,
    DataHeader,
    Frame,
    FrameDecoder,
    ProtocolHeader,
    Security,
    encode_frame,
)

__all__ = [
    "BLOCK_HEADER_SIZE",
    "BLOCK_PLAINTEXT_SIZE",
    "BlockError",
    "BlockHeader",
    "ChecksumMismatch",
    "CommandPacketsDisabled",
    "Compression",
    "DATA_HEADER_SIZE",
    "DataHeader",
    "Direction",
    "Frame",
    "FrameDecoder",
    "FrameTooLarge",
    "MAX_FRAME_LENGTH",
    "PROTOCOL_HEADER_SIZE",
    "PROTOCOL_VERSION",
    "PayloadError",
    "ProtocolError",
    "ListenError",
    "MissingLz4",
    "ProtocolHeader",
    "ReadOnlyParameter",
    "STORED_ONLY",
    "Security",
    "ShortBuffer",
    "UnsupportedCompression",
    "UnsupportedSecurity",
    "UnsupportedVersion",
    "VisionectError",
    "crc32_ieee",
    "decode_blocks",
    "encode_blocks",
    "encode_frame",
    "frame_checksum",
    "have_lz4",
    "iter_block_headers",
    "lz4_compress_block",
    "lz4_decompress_block",
    "stored_only",
    "verify_checksum",
]
