"""Session layer: the sans-io ``DeviceConnection`` and per-UUID device state."""

from .connection import (
    DEFAULT_DEVICE_STATE_POLLING,
    DEFAULT_PACKET_TIMEOUT,
    MIN_WATCHDOG_FIRMWARE_REVISION,
    WATCHDOG_FALLBACK,
    WATCHDOG_JITTER_MAX,
    ConnectionConfig,
    DeviceConnection,
)
from .connection import SLEEP_MIN_MINUTES
from .device import (
    CONVERGENCE_CONTACTS,
    DEFAULT_CONTACT_INTERVAL,
    DRAW_ALLOWANCE,
    RECTANGLE_UNSUPPORTED_HARDWARE,
    DeviceState,
    DeviceStateStore,
    SyncStatus,
)
from .filetransfer import FileRead, FileReadState
from .pending import (
    PENDING_ORDER,
    SLOT_FLASH_SAVE,
    SLOT_FRAMEBUFFER_READ,
    SLOT_GHOST_CLEAR,
    SLOT_IMAGE,
    SLOT_PARAM_READS,
    SLOT_PARAM_WRITES,
    SLOT_REBOOT,
    SLOT_SLEEP,
    PendingWork,
)
from .events import (
    Acked,
    ButtonReceived,
    CborReceived,
    DeviceConnected,
    Event,
    FileEventReceived,
    GpsReceived,
    HeartbeatOverdue,
    Nacked,
    ParamsReceived,
    ProtocolViolation,
    ReadTimeout,
    StatusReceived,
    TouchReceived,
    UnknownPacketType,
    WatchdogFired,
)

__all__ = [
    "Acked",
    "CONVERGENCE_CONTACTS",
    "DEFAULT_CONTACT_INTERVAL",
    "DRAW_ALLOWANCE",
    "FileRead",
    "FileReadState",
    "SyncStatus",
    "ButtonReceived",
    "CborReceived",
    "ConnectionConfig",
    "DEFAULT_DEVICE_STATE_POLLING",
    "DEFAULT_PACKET_TIMEOUT",
    "DeviceConnected",
    "DeviceConnection",
    "DeviceState",
    "DeviceStateStore",
    "Event",
    "FileEventReceived",
    "GpsReceived",
    "HeartbeatOverdue",
    "MIN_WATCHDOG_FIRMWARE_REVISION",
    "Nacked",
    "PENDING_ORDER",
    "PendingWork",
    "SLEEP_MIN_MINUTES",
    "SLOT_FLASH_SAVE",
    "SLOT_FRAMEBUFFER_READ",
    "SLOT_GHOST_CLEAR",
    "SLOT_IMAGE",
    "SLOT_PARAM_READS",
    "SLOT_PARAM_WRITES",
    "SLOT_REBOOT",
    "SLOT_SLEEP",
    "ParamsReceived",
    "ProtocolViolation",
    "RECTANGLE_UNSUPPORTED_HARDWARE",
    "ReadTimeout",
    "StatusReceived",
    "TouchReceived",
    "UnknownPacketType",
    "WATCHDOG_FALLBACK",
    "WATCHDOG_JITTER_MAX",
    "WatchdogFired",
]
